# Generated by Django 4.0.6 on 2022-09-19 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('wound', models.CharField(blank=True, choices=[('F', 'Leg Fracture'), ('H', 'Hematoma'), ('K', 'Knee Sprain'), ('S', 'Sore'), ('A', 'Ankle Sprain')], max_length=1, null=True)),
                ('emergency', models.BooleanField(default=False, verbose_name='emergency')),
                ('secret_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('birthdate',),
            },
        ),
    ]
